### ISSUE TITLE
ChatRoomView

### ISSUE THREAD

**Issue by KangKyung** [KangKyung/Chatting#2]
## 📜 TODO
- [x] 기본 View 구현
- [x] List View 구현
- [x] WritingMessage View 구현

## 📱 PreView
<img src="https://user-images.githubusercontent.com/38858863/163801511-ce9c5c19-f822-4d2c-8843-36536c8d4a64.gif" width="300" />

## 📝 Note
- 말풍선 타입에따라 보낸시간String의 위치를 다르게 만들어야하며, 현재는 hidden을 이용하여 숨겨주고있다. 중복코드를 좀 더 개선하고싶다.
- 메시지를 입력하는 부분을 TextEditor로 구현했는데, 개행이 이루어지면 영역을 넓혀주고싶었으나 잘 되지 않았다.
